[package]
name = "erkan/codenthia_blog"
version = "0.1.0"
description = "Codenthia Blog"

[dependencies]
"wasmer/python" = "3.12"

[[command]]
name = "start"
module = "wasmer/python:python"
runner = "wasi"

[fs]
"/app" = "."

